---

- name: Ensure helm-values folder is present
  file:
    path: helm-values
    state: directory
    mode: 0755

- name: Values parameters file
  template:
    src: templates/values.yaml.j2
    dest: helm-values/gitea.yml

- name: Add gitea chart repo
  community.kubernetes.helm_repository:
    name: gitea-charts
    repo_url: "https://dl.gitea.io/charts/"

- name: Deploy gitea
  community.kubernetes.helm:
    name: gitea
    chart_ref: gitea-charts/gitea
    release_namespace: k8s
    create_namespace: yes
    values_files:
      - helm-values/gitea.yml

