---

collections:
  - name: community.general
    version: "12.2.0"
  - name: ansible.posix
    version: "2.1.0"
  - name: kubernetes.core
    version: "6.2.0"
  - name: community.crypto
    version: "3.1.0"

...
